#include "phaseDetector.h"

char phase_array[4][4] = {
    {NO_CHANGE,FORWARD,ERROR_EVT,BACKWARD},
    {BACKWARD,NO_CHANGE,FORWARD,ERROR_EVT},
    {ERROR_EVT,BACKWARD,NO_CHANGE,FORWARD},
    {FORWARD,ERROR_EVT,BACKWARD,NO_CHANGE}

};